#!/usr/bin/expect -f

set dir [lindex $argv 0]
set ip [lindex $argv 1]

spawn scp -r $dir  "root@$ip:~"
expect {
  "(yes/no)?" {send "yes\r"
               expect "password:"
               send "armored\r"
              }  
  "password:" { send "armored\r"}
}
expect -re $
sleep 2
spawn ssh "root@$ip" "~/demo/setup.sh"
expect {
  "(yes/no)?" {send "yes\r"
               expect "password:"
               send "armored\r"
              }  
  "password:" { send "armored\r"}
}
interact
